---
framework: jasmine
blacklist:
  - 'spec/JUnitXmlReporterSpec.js##JUnitXmlReporter##constructor##file prefix##'
preMerge:
  pattern:
    - "./spec/**/*Spec.js"
preRun:
  - npm i
postRun:
  - node --version
