---
framework: jasmine
blocklist:
 - "spec/JUnitXmlReporterSpec.js##JUnitXmlReporter"
postMerge:
  pattern:
    - "./spec/**/*Spec.js"
preMerge:
  pattern:
    - "./spec/**/*Spec.js"
preRun:
 command:
  - npm i
postRun:
 command:
  - node --version
version: 1.10
  
