---
framework: jasmine
blacklist:
  - 'spec/JUnitXmlReporterSpec.js##JUnitXmlReporter##constructor##file prefix##'
configFile: "./spec/support/jasmine.json"
postMerge:
  pattern:
    - "./spec/**/*Spec.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./spec/**/*Spec.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preRun:
  - npm i
postRun:
  - node --version
version: 2.0
